export const FEATURED_ROOMS_FALLBACK = [
    {
        _id: "fallback-quiet-focus",
        name: "Quiet Focus Room",
        description: "A calm, distraction-free room for solo study, deep work, and exam prep.",
        location: "North Wing",
        capacity: 2,
        pricePerHour: 12,
        amenities: ["Wi-Fi", "Whiteboard", "Power Outlets"],
    },
    {
        _id: "fallback-group-studio",
        name: "Group Prep Studio",
        description: "A bright shared space for presentations, tutoring sessions, and team work.",
        location: "Second Floor",
        capacity: 6,
        pricePerHour: 20,
        amenities: ["Projector", "Wi-Fi", "Air Conditioning"],
    },
    {
        _id: "fallback-window-seat",
        name: "Window Seat Nook",
        description: "A smaller room with natural light and a soft reset from the main stacks.",
        location: "East Wing",
        capacity: 3,
        pricePerHour: 14,
        amenities: ["Quiet Zone", "Power Outlets", "Wi-Fi"],
    },
    {
        _id: "fallback-project-room",
        name: "Project Room",
        description: "Built for workshops, brainstorms, and collaborative planning sessions.",
        location: "Innovation Floor",
        capacity: 8,
        pricePerHour: 24,
        amenities: ["Projector", "Whiteboard", "Wi-Fi"],
    },
    {
        _id: "fallback-commuter-corner",
        name: "Commuter Corner",
        description: "Quick-access desks for short study blocks between classes or transit.",
        location: "Ground Floor",
        capacity: 1,
        pricePerHour: 8,
        amenities: ["Wi-Fi", "Power Outlets"],
    },
    {
        _id: "fallback-creative-den",
        name: "Creative Den",
        description: "A flexible room for sketching ideas, recording notes, or review sessions.",
        location: "South Annex",
        capacity: 4,
        pricePerHour: 16,
        amenities: ["Whiteboard", "Air Conditioning", "Wi-Fi"],
    },
];